trigger:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string
  tags:
    include:
    - 'v*'

pr:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

schedules:
- cron: "0 0 * * 6"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

jobs:
- job: 'WebAssembly'
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'

    - bash: npm install -g yarn
      displayName: "Install Yarn"

    - bash: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      displayName: "Install wasm-pack"

    - task: Cache@2
      inputs:
        key: 'yarn | "$(Agent.OS)" | yarn.lock'
        restoreKeys: |
          yarn | "$(Agent.OS)"
          yarn
        path: $(YARN_CACHE_FOLDER)
      displayName: Cache Yarn packages

    - bash: yarn --frozen-lockfile
      displayName: "Install Deps"

    - bash: sudo node scripts/install_tools.js
      displayName: "Install Tools"

    - bash: yarn build_js --ci
      displayName: "Build"

    - bash: yarn test_js --quiet --ci
      displayName: "Test"
      env:
        PSP_DOCKER: 1

    - task: PublishTestResults@2
      condition: succeeded()
      inputs:
        testRunner: JUnit
        testResultsFiles: 'junit.xml'
    
    # TODO: only artifact the /dist folders inside each package, not the
    # entire packages folder - it probably has to be a new publish task
    # for each package, or maybe we tarball it and copy it back out into
    # the right folder structure.
    - task: PublishPipelineArtifact@1
      condition: succeeded()
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/packages
        artifactName: "perspective-build"

    # TODO: checkout the code in jlab task and stop copying extraneous
    # stuff over
    - task: PublishPipelineArtifact@1
      condition: succeeded()
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/scripts
        artifactName: "perspective-scripts"

    - task: PublishPipelineArtifact@1
      condition: succeeded()
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/package.json
        artifactName: "perspective-package-json"

    - task: PublishPipelineArtifact@1
      condition: succeeded()
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/yarn.lock
        artifactName: "perspective-yarn-lock"

    - task: PublishPipelineArtifact@1
      condition: failed()
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/packages/perspective-viewer/screenshots/'
        artifactName: "perspective-viewer"

    - task: PublishPipelineArtifact@1
      condition: failed()
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/packages/perspective-viewer-datagrid/screenshots/'
        artifactName: "perspective-viewer-datagrid"

    - task: PublishPipelineArtifact@1
      condition: failed()
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/packages/perspective-viewer-d3fc/screenshots/'
        artifactName: "perspective-viewer-d3fc"

    - task: PublishPipelineArtifact@1
      condition: failed()
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/packages/perspective-workspace/screenshots/'
        artifactName: "perspective-workspace"

    - task: PublishTestResults@2
      condition: succeeded()

- job: "Jupyterlab"
  dependsOn: ["WebAssembly", "Linux"]
  pool: 
    vmImage: "ubuntu-16.04"

  steps:
    - checkout: none

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.7'

    - task: NodeTool@0
      inputs:
        versionSpec: "12.x"

    - bash: python -m pip install jupyterlab
      displayName: "Install Jupyterlab"

    - bash: jupyter labextension install @jupyter-widgets/jupyterlab-manager
      displayName: "Install Labextensions"

    - bash: mkdir packages scripts
      displayName: "mkdir"

    # TODO: this needs to be a single zip
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: "perspective-build"
        path: $(System.DefaultWorkingDirectory)/packages
    
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: "perspective-package-json"
        path: $(System.DefaultWorkingDirectory)
        
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: "perspective-yarn-lock"
        path: $(System.DefaultWorkingDirectory)

    # TODO: this should hit the cached versions I think
    - bash: yarn --frozen-lockfile
      displayName: "Install Deps"
    
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: "perspective-scripts"
        path: $(System.DefaultWorkingDirectory)/scripts

    - bash: ls packages
      displayName: "ls"

    - bash: jupyter labextension install packages/perspective-jupyterlab
      displayName: "Install perspective-jupyterlab"

    - bash: jupyter labextension link packages/perspective packages/perspective-viewer packages/perspective-viewer-d3fc packages/perspective-viewer-datagrid
      displayName: "Link local Perspective to Jupyterlab"

    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: "cp37-cp37m-manylinux2010_x86_64"
        path: $(System.DefaultWorkingDirectory)

    - bash: python -m pip install $(System.DefaultWorkingDirectory)/*.whl
      displayName: "Install perspective-python from wheel"

    - bash: cd packages/perspective-jupyterlab && yarn test:jupyter:build && yarn:test:jupyter:run
      displayName: "Run Jupyterlab tests"


- job: 'Linux'
  pool:
    vmImage: 'ubuntu-16.04'

  strategy:
    matrix:
      # Python27ManyLinux2010:
      #   python.version: '2.7'
      #   python_flag: '--python2'
      #   manylinux_flag: '--manylinux2010'
      #   artifact_name: 'cp27-cp27m-manylinux2010_x86_64'
      Python37ManyLinux2010:
        python.version: '3.7'
        python_flag: ''
        manylinux_flag: '--manylinux2010'
        artifact_name: 'cp37-cp37m-manylinux2010_x86_64'

      ${{ if or(startsWith(variables['build.sourceBranch'], 'refs/tags/v'), eq(variables['Build.Reason'], 'Schedule')) }}:
        Python36ManyLinux2010:
          python.version: '3.6'
          python_flag: '--python36'
          manylinux_flag: '--manylinux2010'
          artifact_name: 'cp36-cp36m-manylinux2010_x86_64'
        Python36ManyLinux2014:
          python.version: '3.6'
          python_flag: '--python36'
          manylinux_flag: '--manylinux2014'
          artifact_name: 'cp36-cp36m-manylinux2014_x86_64'
        # Python37ManyLinux2010 is always built
        Python37ManyLinux2014:
          python.version: '3.7'
          python_flag: ''
          manylinux_flag: '--manylinux2014'
          artifact_name: 'cp37-cp37m-manylinux2014_x86_64'
        Python38ManyLinux2010:
          python.version: '3.8'
          python_flag: '--python38'
          manylinux_flag: '--manylinux2010'
          artifact_name: 'cp38-cp38-manylinux2010_x86_64'
        Python38ManyLinux2014:
          python.version: '3.8'
          python_flag: '--python38'
          manylinux_flag: '--manylinux2014'
          artifact_name: 'cp38-cp38-manylinux2014_x86_64'
        Python39ManyLinux2010:
          python.version: '3.9'
          python_flag: '--python39'
          manylinux_flag: '--manylinux2010'
          artifact_name: 'cp39-cp39-manylinux2010_x86_64'
        Python39ManyLinux2014:
          python.version: '3.9'
          python_flag: '--python39'
          manylinux_flag: '--manylinux2014'
          artifact_name: 'cp39-cp39-manylinux2014_x86_64'

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'

    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'

    - bash: npm install -g yarn
      displayName: "Install Yarn"

    - bash: yarn
      displayName: 'Install JS Deps'

    - bash: python -m pip install -U "black==20.8b1" flake8-black pip
      condition: and(succeeded(), ne(variables['python.version'], '2.7'))
      displayName: 'Install Python deps'

    - bash: yarn build_python  --ci $(python_flag) $(manylinux_flag)
      displayName: 'build'
      env:
        PSP_DOCKER: 1

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: 'python/perspective/python_junit.xml'
        testRunTitle: 'Publish test results for Python $(python.version) $(manylinux_flag)'

    - task: PublishCodeCoverageResults@1
      inputs: 
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'

    # Build a python wheel for Manylinux
    - bash: yarn _wheel_python --ci $(python_flag) $(manylinux_flag)
      condition: and(succeeded(), ne(variables['manylinux_flag'], ''))
      displayName: 'Build Manylinux Wheel'
      env:
        PSP_DOCKER: 1

    # Test the wheel
    - bash: cd $(System.DefaultWorkingDirectory)/python/perspective/scripts && ./test_wheels.sh $(python_flag) $(manylinux_flag)
      condition: and(succeeded(), ne(variables['manylinux_flag'], ''))
      displayName: 'Test Manylinux Wheel'

    # Save the artifact to Azure storage
    - task: PublishPipelineArtifact@1
      condition: and(succeeded(), ne(variables['manylinux_flag'], ''))
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/python/perspective/wheelhouse/'
        artifactName: '$(artifact_name)'

- job: 'Windows'
  pool:
    vmImage: 'vs2017-win2016'

  strategy:
    matrix:
      Python37:
        python.version: '3.7'
        python_flag: ''
      ${{ if or(startsWith(variables['build.sourceBranch'], 'refs/tags/v'), eq(variables['Build.Reason'], 'Schedule')) }}:
        Python36:
          python.version: '3.6'
          python_flag: '--python36'
        Python38:
          python.version: '3.8'
          python_flag: '--python38'
        Python39:
          python.version: '3.9'
          python_flag: '--python39'

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'

    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'

    - script: |
        which python > python.txt
        set /p PYTHON=<python.txt
        ln -s %PYTHON% %PYTHON%$(python.version)
        python --version
        which python$(python.version)
      displayName: "Which python"

    - script: |
        python -m pip install -U numpy "pyarrow>=2" pip
      displayName: "Python deps"

    - script: npm install -g yarn
      displayName: "Install Yarn"

    - script: yarn
      displayName: 'Install JS Deps'

    - script: choco install boost-msvc-14.1 flatc
      displayName: "System deps"

    - script: yarn build_python --ci $(python_flag)
      displayName: 'build'

- job: 'MacOS_Catalina'
  pool:
    vmImage: 'macos-10.15'

  strategy:
    matrix:

      Python37:
        python.version: '3.7'
        python_flag: ''
        artifact_name: 'cp37-cp37m-macosx_10_15_x86_64'
      Python39:
        python.version: '3.9'
        python_flag: '--python39'
        artifact_name: 'cp39-cp39-macosx_10_15_x86_64'

      ${{ if or(startsWith(variables['build.sourceBranch'], 'refs/tags/v'), eq(variables['Build.Reason'], 'Schedule')) }}:
        Python36:
          python.version: '3.6'
          python_flag: '--python36'
          artifact_name: 'cp36-cp36m-macosx_10_15_x86_64'
  
        Python38:
          python.version: '3.8'
          python_flag: '--python38'
          artifact_name: 'cp38-cp38-macosx_10_15_x86_64'

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'

    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'

    - script: |
        brew install boost flatbuffers
      displayName: "System deps"

    - script: |
        which python
        python --version
        which python$(python.version)
      displayName: "Which python"

    - script: |
        python -m pip install -U delocate wheel numpy "pyarrow>=2" pip
      displayName: "Python deps"
      condition: eq(variables['python_flag'], '')
    
    - script: npm install -g yarn
      displayName: "Install Yarn"

    - script: yarn --network-timeout 600000
      displayName: 'Install JS Deps'

    - script: yarn build_python --ci $(python_flag)
      displayName: 'build'

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: 'python/perspective/python_junit.xml'
        testRunTitle: 'Publish test results for Python $(python.version)'

    - task: PublishCodeCoverageResults@1
      inputs: 
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'

    # Build a python wheel for Mac 10.14
    - bash: yarn _wheel_python --ci $(python_flag) --macos
      displayName: 'Build wheel'

    # Test the wheel
    - bash: cd $(System.DefaultWorkingDirectory)/python/perspective/scripts && ./test_wheels.sh $(python_flag) --macos
      displayName: 'Test Mac Wheel'

    # Save the artifact to Azure storage
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/python/perspective/dist/'
        artifactName: '$(artifact_name)'