[package]
name = "rust_example"
version = "0.1.0"
authors = ["Jun Tan <tanjunyuan@hotmail.co.uk>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
cty = "0.2.1"
libc = "0.2.80"
rand = "0.7.3"
